apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app1
spec:
  selector:
    matchLabels:
      app: sample-app1
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app1
    spec:
      containers:
      - name: http-echo
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80
        - containerPort: 443

---

kind: Service
apiVersion: v1
metadata:
  name: sample-app1
spec:
  type: NodePort
  selector:
    app: sample-app1
  ports:
    - port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /sample-app1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: sample-app1
            port:
              number: 80