apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app1
spec:
  selector:
    matchLabels:
      app: sample-app1
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app1
    spec:
      containers:
      - name: http-echo
        image: mendhak/http-https-echo
        ports:
        - containerPort: 80
        - containerPort: 443